version: '3.8'

services:
  mysql_db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: onlinebookstore
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bookstore_net

  tomcat_app:
    image: onlinebookstore
    container_name: tomcat_app
    depends_on:
      - mysql_db
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql_db
      - DB_USER=root
      - DB_PASSWORD=Chandu_0000
    networks:
      - bookstore_net

volumes:
  mysql_data:

networks:
  bookstore_net:
    driver: bridge
